services:

    koalamonintegration.initPlugin:
        class: Koalamon\PluginBundle\EventListener\KernelRequestListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request' }