koalamon_notification_engine_home:
    path:     /p/{project}/notifications/
    defaults: { _controller: KoalamonNotificationEngineBundle:Default:index }

koalamon_notification_engine_create:
    path:     /p/{project}/notifications/create/{senderIdentifier}/
    defaults: { _controller: KoalamonNotificationEngineBundle:Default:create }

koalamon_notification_engine_delete:
    path:     /p/{project}/notifications/delete/{notificationConfiguration}/
    defaults: { _controller: KoalamonNotificationEngineBundle:Default:delete }

koalamon_notification_engine_edit:
    path:     /p/{project}/notifications/edir/{notificationConfiguration}/
    defaults: { _controller: KoalamonNotificationEngineBundle:Default:edit }

koalamon_notification_engine_store:
    path:     /p/{project}/notifications/store/
    defaults: { _controller: KoalamonNotificationEngineBundle:Default:store }


# alerts
koalamon_notification_engine_alerts_home:
    path:     /p/{project}/alerts/
    defaults: { _controller: KoalamonNotificationEngineBundle:Alerts:index }

koalamon_notification_engine_alerts_edit:
    path:     /p/{project}/edit/{notificationConfiguration}/
    defaults: { _controller: KoalamonNotificationEngineBundle:Alerts:edit }

koalamon_notification_engine_alerts_store:
    path:     /p/{project}/store/{notificationConfiguration}/
    defaults: { _controller: KoalamonNotificationEngineBundle:Alerts:store }