koalamon_default_event_knownissue_mark:
    path:     /p/knownissue/mark/{eventIdentifier}/
    defaults: { _controller: KoalamonDefaultBundle:Event:markAsKnownIssue }

koalamon_default_event_knownissue_unmark:
    path:     /p/knownissue/unmark/{eventIdentifier}/
    defaults: { _controller: KoalamonDefaultBundle:Event:unMarkAsKnownIssue }

koalamon_default_homepage:
    path:     /
    defaults: { _controller: KoalamonDefaultBundle:Default:index }

koalamon_default_imprint:
    path:     /we/imprint.html
    defaults: { _controller: KoalamonDefaultBundle:Default:imprint }

koalamon_user_homepage:
    path:     /user/
    defaults: { _controller: KoalamonDefaultBundle:User:index }

koalamon_default_project_create:
    path:     /p/create/
    defaults: { _controller: KoalamonDefaultBundle:Project:create }

koalamon_default_project_create:
    path:     /p/store/
    defaults: { _controller: KoalamonDefaultBundle:Project:store }

koalamon_default_project_admin:
    path:     /p/{project}/admin/
    defaults: { _controller: KoalamonDefaultBundle:Project:admin }


koalamon_default_project_translation_store:
    path:     /p/{project}/translation/store/
    defaults: { _controller: KoalamonDefaultBundle:Project:storeTranslation }

koalamon_default_project_translation_delete:
    path:     /p/{project}/translation/delete/
    defaults: { _controller: KoalamonDefaultBundle:Project:deleteTranslation }


# project
koalamon_default_project_admin_store:
    path:     /p/{project}/admin/project/store
    defaults: { _controller: KoalamonDefaultBundle:Project:storeOptions }

# tools
koalamon_default_tool_admin:
    path:     /p/{project}/admin/tools/
    defaults: { _controller: KoalamonDefaultBundle:Tool:admin }

koalamon_default_project_tool_store:
    path:     /p/{project}/admin/tools//store/
    defaults: { _controller: KoalamonDefaultBundle:Tool:store }

koalamon_default_project_tool_delete:
    path:     /p/{project}/admin/tools/delete/
    defaults: { _controller: KoalamonDefaultBundle:Tool:delete }

# collaborators
koalamon_default_user_admin:
    path:     /p/{project}/admin/user/
    defaults: { _controller: KoalamonDefaultBundle:User:admin }

koalamon_default_user_admin_collaborator_add:
    path:     /p/{project}/admin/user/collaborator/add/
    defaults: { _controller: KoalamonDefaultBundle:User:addCollaborator }

koalamon_default_user_admin_collaborator_remove:
    path:     /p/{project}/admin/user/collaborator/remove/
    defaults: { _controller: KoalamonDefaultBundle:User:removeCollaborator }

#systems
koalamon_default_system_admin:
    path:     /p/{project}/admin/systems/
    defaults: { _controller: KoalamonDefaultBundle:System:admin }

koalamon_default_admin_system_store:
    path:     /p/{project}/admin/system/store/
    defaults: { _controller: KoalamonDefaultBundle:System:storeSystem }

koalamon_default_admin_subsystem_store:
    path:     /p/{project}/admin/subsystem/store/
    defaults: { _controller: KoalamonDefaultBundle:System:storeSubSystem }

koalamon_default_admin_system_delete:
    path:     /p/{project}/admin/system/delete/
    defaults: { _controller: KoalamonDefaultBundle:System:deleteSystem }